### ISSUE TITLE
Emacs hangs when I run a dumb-jump search command (macOS, emacs 25.1, vanilla install).

### ISSUE THREAD

**Issue by adc17** [jacktasia/dumb-jump#101]
Hi jacktasia,
I've just installed dumb-jump on a new MacBook Pro running OS 10.12, and I'm trying it out on a small (11kb) project. I'm having no luck—dumb-jump just hangs for ~20 seconds and doesn't successfully jump to the definition. 
I have ag and ripgrep installed; I'm using vanilla emacs 25.1 (nothing except dumb-jump and its dependencies), and I've tried this with both the melpa and the melpa-stable builds. 
Your package worked fine for me on ubuntu—have you encountered problems with macOS before, and can you suggest what might be going on?

**Comment by jacktasia** [comment]
I use macOS with no problems. What language is your small project in?

**Comment by adc17** [comment]
It's in ruby. Apologies, as I've just tried the `(setq dumb-jump-default-project "~/path/to/project")` code and it fixed the issue for me.

**Comment by adc17** [comment]
In what sort of scenarios does dumb-jump struggle to identify the root project folder? It would be helpful to know moving forwards.

**Comment by jacktasia** [comment]
It's going to keep looking at parent directories of your currently open file until it sees one of these files: https://github.com/jacktasia/dumb-jump/blob/master/dumb-jump.el#L780

A better solution for you would be to just create a `.dumbjump` file in that root of your project (more details in README). Usually this isn't necessary because 99% of projects seem to be using a VCS (particularly git). So basically if you're not using a VCS then you'll want to create a `.dumbjump` file.
