### ISSUE TITLE
dumb-jump not finding declaration in extremely simple C example

### ISSUE THREAD

**Issue by wtok** [jacktasia/dumb-jump#128]
It's likely this is a problem with my setup, but I can't get dumb-jump to work for C at all.

Here's what I'm trying to get working. I have a folder with just two files in it, `test.c` and `test.h`. 

This is `test.c`:
```c
#include "test.h"
int main(void) { some_function(); return 0; }
```

And this is `test.h`:
```c
void some_function(void) { return; }
```

If I navigate to `some_function()` in `test.c` and do `M-x dumb-jump-go` or any other `dumb-jump` command, it fails to find the declaration of `some_function` in `test.h`. Changing the whitespace around doesn't seem to change anything.

Can anyone reproduce this? It seems like the simplest possible use case for the program. I'm convinced it must be a problem with my setup, but I don't know.

Thanks.

**Comment by wtok** [comment]
Okay, thanks for that. I couldn't get it to print any debug info, so I tried deleting and re-installing dumb-jump, which solved the issue and it now works as expected. I have no idea how my dumb-jump package got broken like that, but it's fixed now. Thanks!

**Comment by josefig** [comment]
Hello @jacktasia 

Just for the record. I tried this example and didn't work, my *Mesages* were showing with rg that was not working because the build I had didn't support PCRE2. So I tried with grep but this version of grep didn't have the --include option. After trying I found that the ag (the silver searcher) is working now.

I am using OpenBSD -current. So maybe if someone else is using OpenBSD might find this useful. Thanks.

----- *Messages * -----

DUMB JUMP DEBUG ‘dumb-jump-run-command‘ START
----

cmd:
	rg --color never --no-heading --line-number -U --pcre2 --type c --type cpp \\bsome_function\(\\s\|\\\)\)\*\\\(\(\\w\|\[\,\&\*.\<\>\:\]\|\\s\)\*\(\\\)\)\\s\*\(const\|-\>\|\\\{\|\$\)\|typedef\\s\+\(\\w\|\[\(\*\]\|\\s\)\+some_function\(\\\)\|\\s\)\*\\\(\|\\b\(\?\!\(class\\b\|struct\\b\|return\\b\|else\\b\|delete\\b\)\)\(\\w\+\|\[\,\>\]\)\(\[\*\&\]\|\\s\)\+some_function\\s\*\(\\\[\(\\d\|\\s\)\*\\\]\)\*\\s\*\(\[\=\,\(\)\{\;\]\|\:\\s\*\\d\)\|\#define\\s\+some_function\\b\|\\b\(class\|struct\|enum\|union\)\\b\\s\*some_function\\b\\s\*\(final\\s\*\)\?\(\:\(\(\\s\*\\w\+\\s\*\:\:\)\*\\s\*\\w\*\\s\*\<\?\(\\s\*\\w\+\\s\*\:\:\)\*\\w\+\>\?\\s\*\,\*\)\+\)\?\(\(\\\{\|\$\)\)\|\}\\s\*some_function\\b\\s\*\; /home/josefig/Documents/projects/c-test

rawresults:
	PCRE2 is not available in this build of ripgrep



-----
DUMB JUMP DEBUG ‘dumb-jump-run-command‘ END
-----
DUMB JUMP DEBUG ‘nil‘ START
----

look-for:
	some_function

(plist-get info :ctx-type):
	

var-to-jump:
	nil

(pp-to-string match-cur-file-front):
	nil

(pp-to-string results):
	nil

match-cur-file-front:
	nil

proj-root:
	/home/josefig/Documents/projects/c-test

(plist-get info :file):
	/home/josefig/Documents/projects/c-test/test.c


-----
DUMB JUMP DEBUG ‘nil‘ END
-----
’some_function’ c++  declaration not found.
user-error: No definitions found for: some_function
