### ISSUE TITLE
Support tramp

### ISSUE THREAD

**Issue by ewstearns** [jacktasia/dumb-jump#137]
Works on a emacs running on remote, but doesn't work over tramp. 

Host: GNU Emacs 25.1.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2016-09-17

Remote: GNU Emacs 24.5.1 (x86_64-pc-linux-gnu) of 2016-04-17 on lgw01-04, modified by Debian

The only difference I can see between working and not working is tramp.

**Comment by jacktasia** [comment]
Thanks for the report. I honestly thought I had just used it via `tramp` the other day and it worked fine. All I had to do was install `ag` on the remote host and it worked, but there's tons of different ways to use `tramp` so that could be the difference. FWIW I was using a mac and the `scpx` tramp method and had `ssh-copy-id`'d to the remote. 

That said, I am confused why you're mentioning two versions of emacs because my understanding is `tramp` uses your local emacs to make a connection to a remote machine directly and another emacs doesn't actually come into play, but maybe this is just another way to use it?

To figure this out I am going to need more information. Please tell me

1) your `tramp-default-method`
2) the searcher you're trying to use (default, `ag`, etc) (my early guess is that the default `git-grep` doesn't work, but `ag` will so you might want to try this first)
3) the programming language of your project

Thanks!

**Comment by ewstearns** [comment]
1. `tramp-default-method` is `scp`.
2. I'm trying to use `ag`. 

I turned on `dumb-jump-debug` and got the following in my `*Messages*` buffer (editted to remove sensitive data):

~~~
-----
DUMB JUMP DEBUG ‘dumb-jump-run-command‘ START
----- 

cmd: 
	ag --nocolor --nogroup --cc --cpp \\bClassName\(\\s\|\\\)\)\*\\\(\(\\w\|\[\,\&\*.\<\>\]\|\\s\)\*\(\\\)\)\\s\*\(const\|-\>\|\\\{\|\$\)\|typedef\\s\+\(\\w\|\[\(\*\]\|\\s\)\+ClassName\(\\\)\|\\s\)\*\\\(\|\\b\(\?\!\(class\\b\|struct\\b\|return\\b\|else\\b\|delete\\b\)\)\(\\w\+\|\[\,\>\]\)\(\[\*\&\]\|\\s\)\+ClassName\\s\*\(\\\[\(\\d\|\\s\)\*\\\]\)\*\\s\*\(\[\=\,\(\)\{\;\]\|\:\\s\*\\d\)\|\#define\\s\+ClassName\\b\|\\b\(class\|struct\|enum\|union\)\\b\\s\*ClassName\\b\\s\*\(final\\s\*\)\?\(\:\(\(\\s\*\\w\+\\s\*\:\:\)\*\\s\*\\w\*\\s\*\<\?\(\\s\*\\w\+\\s\*\:\:\)\*\\w\+\>\?\\s\*\,\*\)\+\)\?\(\(\\\{\|\$\)\)\|\}\\s\*DataBroadcastIdDescriptor\\b\\s\*\; /scp:mars:/home/user/src/subdirectory

raw results: 

	ERR: Error stat()ing: /scp:remote:/home/user/src/project
ERR: Error opening directory /scp:remote:/home/user/src/project/subdirectory: No such file or directory
 

-----
DUMB JUMP DEBUG ‘dumb-jump-run-command‘ END
-----
~~~
