### ISSUE TITLE
distinguish definition from references

### ISSUE THREAD

**Issue by tjaartvdwalt** [jacktasia/dumb-jump#151]
First off, I love dumb-jumb. Thanks for a great project.

I did not have to configure much to get it working. With this "default" config, I get a popup menu with the completion options. Most of the lines are other references to the function, and one is the function definition itself.

Often I want to go to the definition, and sometimes I find it hard to spot. Is there a way that the definition could be either: 1) at the top of the list or 2) in a highlighted line?

**Comment by jacktasia** [comment]
Thanks for the kind words and for opening this issue. I agree it's a good idea to display the definition type when displaying results. That said, this could be a bug in dumb-jump or an edge case where it seems wrong because of something unique to your project because having to choose, particularly between different types of definitions should be pretty rare (from my experience).

For some languages, we support both function and variable definitions (and sometimes more) and there's a fallback enabled by default where if we can't find a definition we just search for the symbol itself, which if we don't have a complete set of definitions for that language could provide a weird experience (see number 2 below).

Some things that could possibly be happening

1) In the same project, a symbol could be used as both a variable and function in multiples places. Consider `function display() {` vs `var display = 'monitor'` vs `let display = function() {`. If like javascript dumb-jump supports both types then there's no obvious place to jump to then we'll give the choice, which would provide a mixture of types and what I think/hope is the case for you.

2) Alternatively, you could be using a language that only has one type of definition (say function), but your project only contains the other (say variable), and to get even more complex you could _actually_ have both, but dumb-jump doesn't have a rule for one of the other cases so you're getting a mixture.

Anyway, since there are so many possibilities for why you're not always having a good experience I'd really appreciate it if you could provide the language(s) and symbols in questions and ideally a screenshot so I can figure out what's happening and see if there's a bigger issue/bug with dumb-jump, but again, I totally agree that regardless it'd be better to highlight definitions types in some way.

 In the short term, I'd suggest setting `dumb-jump-selector` to `helm` or `ivy` as I feel like they provide a much better experience when there are more choices/characters choose from.

Thanks again for opening this!

**Comment by tjaartvdwalt** [comment]
Thanks for the explanation.

Currently I am writing Ruby. (see screenshot below)

In this example I executed dumb-jump on the `file_it` method.

![2017-07-25-095348_swaygrab](https://user-images.githubusercontent.com/2066766/28583778-3802c702-711f-11e7-8c03-41f8767e6d08.png)

**Comment by tjaartvdwalt** [comment]
I set the `ivy` selector as you suggested in your original post. This makes it much easier to find the definition (in the Ruby case I simply narrow using `def`)

If you want, we can close this bug.

**Comment by netromdk** [comment]
Let's close this, @jacktasia?

**Comment by jacktasia** [comment]
@netromdk Sounds good. Closing.
