### ISSUE TITLE
Elixir/Alchemist Go To Definition brings "Visit tags table" quickfix

### ISSUE THREAD

**Issue by svileng** [jacktasia/dumb-jump#167]
I originally posted this issue on Spacemacs' repo:

syl20bnr/spacemacs#9756

But sounds like it was more appropriate to report here. Please let me know if there is any other info I could provide to help fixing the problem.

Thanks!

**Comment by jacktasia** [comment]
Thanks for the report. I am not sure where `Visit tags table (default TAGS): ` is coming from, but it's not dumb-jump. It doesn't use TAGS, which is kind of the whole point of this project. 

Some ideas:

Check what `SPC m g g` is bound to. I am guessing Elixir has some other layer/package installed. 

Try manually triggering `dumb-jump-go` instead of using the above keybinding. 

Please let me know how it goes. Thanks!

**Comment by svileng** [comment]
Thanks for the suggestions @jacktasia!

Using dumb-jump-go manually does seem to work, so it is indeed not an issue with the package. I'm relatively new to Spacemacs/Emacs — do you know how can I find out what is the package responsible for `SPC m g g` shortcut in Elixir mode?

Thanks a lot!

**Comment by jacktasia** [comment]
@svileng If you manually call `describe-key` and do <kbd>SPC m g g</kbd> it will tell you what it's bound to, by default `describe-key` is bound to <kbd>C-h k</kbd> and it looks like it's <kbd>SPC h d k</kbd> in spacemacs

Here's where I found that:
https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#getting-help
