### ISSUE TITLE
Customizable key bindings?

### ISSUE THREAD

**Issue by HeroInNoMan** [jacktasia/dumb-jump#18]
Hello,

"C-M-p" is already used by (backward-list), a pretty useful command. Would it be possible to let the key-bindings to the user or at least make them customizable, so that (dumb-jump-back) could be bound somewhere else?

Anyhow, thank you for this great package!

**Comment by jacktasia** [comment]
Absolutely. The easiest thing would be to just _not_ use `(dumb-jump-mode)`. All this mode does is activate the `dumb-jump-mode-map` with default bindings.

So instead just do something like this in your `~/.emacs`:
```
(require 'dumb-jump)
(global-set-key (kbd "C-c ?") 'dumb-jump-go)
```

The `interactive` functions are: `dumb-jump-go` `dumb-jump-back` `dumb-jump-quick-look`

Alternatively, you could do [something like this](http://ergoemacs.org/emacs/reclaim_keybindings.html).

Please re-open if the above does not help.

**Comment by HeroInNoMan** [comment]
Great, thanks a lot. I just removed (dumb-jump-mode) from my config and added the desired key-bindings, works perfectly.
Thank you for the quick answer!

**Comment by Yevgnen** [comment]
Just curious, why not make `dumb-jump-mode` *local* minor mode?

**Comment by Yevgnen** [comment]
@jacktasia Hi, I saw `:global t` where `dumb-jump-mode` is defined. Defining the keybindings via `use-package` is one of the solutions. But since `dumb-jump-mode` is global, it overwrites any other `C-M-g`, `C-M-p` and `C-M-q` defined in other minor modes. For example, I would like to use `dump-jump-mode` in `python-mode`, `C-mode` using the above key bindings, but not in `java-mode`, `lua-mode`. With `dump-jump-mode` enabled, the original key bindings in `java-mode` or `lua-mode` is overwritten. Personally, I prefer something like

```
(add-hook 'python-mode-hook #'dumb-jump-mode) ; local
```

to 

```
(dump-jump-mode 1) ; global
```
