### ISSUE TITLE
Failing to load dumb-jump-quick-look: autoload failed to define function

### ISSUE THREAD

**Issue by vmalloc** [jacktasia/dumb-jump#233]
I am using dumb-jump through use-package:
```lisp
(use-package dumb-jump
  :ensure
  :bind (("M-g M-o" . dump-jump-quick-look)))
```

When I try to trigger it, I get:
```
command-execute: Autoloading file /Users/vmalloc/.emacs.d/elpa/dumb-jump-20180930.550/dumb-jump.elc failed to define function dump-jump-quick-look
```

**Comment by jacktasia** [comment]
@vmalloc Looks like you have a typo. You have `dump-jump-quick-look` and it should be `dumb-jump-quick-look` (`p` -> `b`).

**Comment by jacktasia** [comment]
Thanks for opening this, btw. This is a really easy typo to make for me (because of DB dumps). I make it often and this just triggered me to check the repo. I had two of these in the readme: https://github.com/jacktasia/dumb-jump/commit/242cc0a14d1c13aef32c3e4653ac60e1aa0832e0

I am going to close this for now, but please re-open if you continue to have issues. Thanks!

**Comment by vmalloc** [comment]
Doh - I feel so stupid now... Thanks and sorry for the hassle!
