### ISSUE TITLE
Question: how to .dumbjumpignore in bulk?

### ISSUE THREAD

**Issue by krsoninikhil** [jacktasia/dumb-jump#252]
This in continuation to #103 (#36).
Problem with `.dumbjumpignore` is, I have multiple child git repositories and adding ignore file in each is pain and also clutter for collaborators not using Emacs.

So is it possible to specify directories to ignore in `.dumbjump` itself (may prefixed with !) or just prefer the project root with `.dumbjump` file in it over `.git`?

**Comment by jacktasia** [comment]
> Problem with .dumbjumpignore is, I have multiple child git repositories and adding ignore file in each is pain and also clutter for collaborators not using Emacs.

I guess either adding the `.dumpjumpignore` file is worth the payoff or it isn't. You wouldn't be required to actually commit/push your `.dumbjumpignore` and could add it to your `.gitignore` so there would no impact for non-emacs users. I would need to know more about your directory structure, but I am guessing it would be straightforward to just write a script to temporary insert them. I'd be willing to help write that if you can share your folder structure.

> So is it possible to specify directories to ignore in .dumbjump itself (may prefixed with !) or just prefer the project root with .dumbjump file in it over .git?

Yes, this is documented in the [.dumbjump section of the README.](https://github.com/jacktasia/dumb-jump#example-dumbjump), but this won't help you in your case because if you jump from a child repo without a `.dumbjumpignore` it's never going to have the opportunity to reach the project root's `.dumpjump` to read it.

**Comment by krsoninikhil** [comment]
Overriding the denoters list with `setq` seems great and rewriting config for this might not be a good idea.
