### ISSUE TITLE
SV jump to class handle not working

### ISSUE THREAD

**Issue by DeeeeLAN** [jacktasia/dumb-jump#266]
Hi, amazing plugin. I have the following SV code:

```
	pfm_ctrl_c21_apb_v1_sal_c sal;
	sal = new();
	sal.tb_if = tb_if;
```

Only the second and third lines show up in the tooltip for `sal`. I would like to be able to jump to the first line, so I can then jump to the class definition.

**Comment by jacktasia** [comment]
> Hi, amazing plugin.

Thanks!

> I would like to be able to jump to the first line, so I can then jump to the class definition.

My first thought is there's not a lot of context on that line and while I could certainly write a regular expression to match it I would be afraid of false positives since I don't know SV very well at all.

I'll take a closer look after work and see if I can get this working without introducing false positives.

**Comment by DeeeeLAN** [comment]
Thanks. It is true that there isn’t a lot of context, but it is basically

[class name] [instance handle declaration];

There will be few (I can’t think of any other) cases in SV that has that short of syntax, except for handle declarations.

Thanks,
Dillan

________________________________
