### ISSUE TITLE
Is there a way to automatically ignore backup files?

### ISSUE THREAD

**Issue by EskoJTH** [jacktasia/dumb-jump#275]
Emacs by default creates a ~ file and # file. Is there a way to skip the results from those? I don't need every result showing trice. I would like to also prevent some log files from showing. But I also would wish to not have to make this edit to every individual file. What kind of solutions do you others use for this?

**Comment by jacktasia** [comment]
I personally turn off the emacs backups with this: `(setq make-backup-files nil)`. Another solution would be to configure the backups to go to a different directory instead of within the project itself, which you can read more about here: https://stackoverflow.com/questions/151945/how-do-i-control-how-emacs-makes-backup-files
