### ISSUE TITLE
Minibuffer window is not active

### ISSUE THREAD

**Issue by vicwer** [jacktasia/dumb-jump#286]
You can run the command ‘dumb-jump-go’ with C-M-g
Took over 2s to find ’split’. Please install ag or rg, or add a .dumbjump file to ’/home/user’ with path exclusions
user-error: Minibuffer window is not active
emacs-25, how to use it, pls?

**Comment by jacktasia** [comment]
@vicwer Sounds like you're trying to jump in an undefined project. Usually, it will automatically find the project root by looking for [one of these files](https://github.com/jacktasia/dumb-jump/blob/master/dumb-jump.el#L1450) since most projects use version control like git this is rarely a problem. In your case, it's probably defaulting to your home directory, which probably has too much stuff to search quickly

Try adding an empty `.dumbjump` to the root of the project. Issue #128 is probably related. I hope this helps. Please let me know if you continue to have issues.

**Comment by vicwer** [comment]
@jacktasia Hello, I add an empty ```.dumpjump``` in my project, it's worked!
That's awesome~~~Thank you very much !!!

**Comment by jacktasia** [comment]
Happy to hear you got it working. Thanks for letting me know.
