### ISSUE TITLE
Consider a different project name?

### ISSUE THREAD

**Issue by soamvasani** [jacktasia/dumb-jump#316]
Hi! First off, thank you for this excellent project and for making it free.  I've use it many times a day since I first installed it, and it's always worked great.

But recently I had to install it on a new machine and I realized the project name is a bit ableist -- I'm not disabled but I've become quite uncomfortable using the word dumb to mean "unsophisticated", and I can only imagine how bad it would make a disabled person feel.

I know it's a substantial effort, but IMHO inclusion is worthwhile, so I hope you'll consider it!  If you're willing to change the name, I'd be more than happy to help with the actual work of doing that.  Thanks! :)

**Comment by jacktasia** [comment]
Thanks for opening this. I appreciate the spirit of your request, and as someone who started their career making software for teachers of people with cognitive disabilities, it's not something that I take lightly. There are definitely words I will not use because of this. That said, I believe language evolves and never at least in my life has "dumb" been used to mean what you're implying, and [emacs itself has dozens of instances of 
"dumb" in this way](https://github.com/emacs-mirror/emacs/search?q=dumb&unscoped_q=dumb). If the rest of the emacs community wants to remove this word then I will certainly consider following them, but until then I think the energy can be put to better use.

**Comment by apaleslimghost** [comment]
i don't think "everybody else does this" and "we've got other things to work on" are good enough but that's just me 🤷‍♀️
