### ISSUE TITLE
Why prefer ag over rg?

### ISSUE THREAD

**Issue by ianpan870102** [jacktasia/dumb-jump#318]
I'd love to see a benchmark between git-grep, ag, and rg.
To my knowledge, rg is supposed to be faster than ag, so I was wondering if there's a specific reason you chose ag over rg. Of course, users can do `(setq dumb-jump-prefer-searcher 'rg)` to explicitly prefer rg, but I'd love dumb-jump to have the best defaults, making this project even greater! Again, dumb-jump is awesome, thank you for this!

**Comment by jacktasia** [comment]
> I'd love to see a benchmark between git-grep, ag, and rg.

I would also be interested to see this and happy to take a PR if someone thinks they have a good generalized example, but personally I've seen too much variance on common cases and I've never seen too much of a speed difference between these 3 to ever feel motivated to use anything other than `ag`

> I was wondering if there's a specific reason you chose ag over rg. 

The main reasons that `ag` is preferred over `rg`:

1. `ag` has existed for longer and so has had better support in dumb-jump for longer
2. lots of builds of `rg` do not get built with `pcre` support which means some of the generalized regular expressions will not work and so often this means less support within dumb-jump because a regex will not end up getting tagged as `rg`

> dumb-jump is awesome, thank you for this!

Thanks for saying this. You're very kind.

**Comment by ianpan870102** [comment]
> I've never seen too much of a speed difference between these 3

This is quite true. I've tested these commands on my machine without benchmarking, and tbh there's no human-noticeable difference.

> The main reasons that ag is preferred over rg:

Thanks for the explanation, this answers my question exactly.

> Thanks for saying this.

Of course! Thank "you"
