### ISSUE TITLE
root project error

### ISSUE THREAD

**Issue by cool0looc** [jacktasia/dumb-jump#329]
Hi,

I'm using dumb-jump with doom-emacs. I enabled dumb-jump-debug and using "ag as the default searcher". But some git project works fine, some are not. I created also ".dumbjump" file in the root directory. 
The debug info always indicates the search directory is in the current directory.
" \ag --nocolor --nogroup --cc --cpp \\bsht2x_init\(\?\!\[a-zA-Z0-9\\\?\\\*-\]\) /home/coollooc/RIOT/examples/hello-world"
How can I change the default search directory?

Thanks,

**Comment by jacktasia** [comment]
Thanks for opening this and sorry for the delay in responding. 

> But some git project works fine, some are not. I created also ".dumbjump" file in the root directory.

Can you provide an example of a publically available git project that doesn't work for you? By default it will look at each parent directory until it sees a project denoter:
https://github.com/jacktasia/dumb-jump/blob/90369d93cacf6efc1bf9a619439abef5ea957e26/dumb-jump.el#L1608

So it's possible it's finding one of those before your `.dumbjump` file. You may also want to look at the options `dumb-jump-default-project` and  `dumb-jump-project`

**Comment by cool0looc** [comment]
Hi Jacktasia,
Thanks for replying. Just check the project: https://github.com/RIOT-OS/RIOT.
In the root folder:
![root_folder](https://user-images.githubusercontent.com/62760352/78787934-5fb09d00-79ab-11ea-9aec-69de7fc07a23.png)

There is .git directory.
Now my emacs is working in example/hello-world/main.c
![hello](https://user-images.githubusercontent.com/62760352/78788233-ca61d880-79ab-11ea-83d2-f8e485a14a8a.png)

Just made a request on "RIOT_BOARD", the debug window is:
![debug](https://user-images.githubusercontent.com/62760352/78788272-d9488b00-79ab-11ea-82ff-5e1376ca7eb8.png)
There is no any project denoter ".git .dumbjump" in the directory
![dir](https://user-images.githubusercontent.com/62760352/78788356-fa10e080-79ab-11ea-8283-63e21d2767e5.png)

But the search in still in the current directory.

**Comment by bgwines** [comment]
+1, I am experiencing this same issue

**Comment by bgwines** [comment]
ah, my issue was actually different. It recognized the project root correctly, but when navigating to a file, it would navigate relative to the current directory instead of relative to the project root.

I think this is probably a different bug with dumb-jump when it is configured to use `git grep`, since the output of `git grep` uses relative paths (relative to project root), not absolute. So it would attempt to navigate to `directory_of_current_buffer/path/relative/to/project/root`, even though the grep had indeed identified the correct path.

I can file another issue for this if you want, @cool0looc, but it's low priority to me since I was able to fix it with `(setq dumb-jump-force-searcher 'ag)`, which is recommended anyway, so it's probably not common for people to encounter this issue.

**Comment by jacktasia** [comment]
@cool0looc

> There is no any project denoter ".git .dumbjump" in the directory

This is not true, because `Makefile` is a project denoter.

Are you trying to jump out of your `example` project and into `RIOT` for a function declaration?

**Comment by cool0looc** [comment]
@jacktasia 

Thanks, you are right. 

I didn't pay attention to Makefile is also a project denoter.
