### ISSUE TITLE
Add Swift support

### ISSUE THREAD

**Issue by wiruzx** [jacktasia/dumb-jump#43]

**Comment by jacktasia** [comment]
@wiruzx @nathankot @jojojames Dumb Jump with Swift support is now available via MELPA. Please let me know if you have any feedback. Thanks!

**Comment by jojojames** [comment]
Will do, thanks!

**Comment by jojojames** [comment]
@jacktasia 

The swift support works great. I think where it falls a little is when trying to jump to an ObjC declaration from a Swift file (and vice versa) due to the languages have interop with each other. Similarly (java<->kotlin) and maybe (erlang<->elixir).

It might be nice to support that kind of jump. Maybe I can support it in smart-jump if it's not appropriate in dumb-jump if there was an API to use (maybe just programmatically changing the major-mode before a dumb-jump would work).

**Comment by jacktasia** [comment]
@jojojames Thanks, good points. Let me think about this a bit and get back to you. Made a new issue so this doesn't get lost: https://github.com/jacktasia/dumb-jump/issues/192
