### ISSUE TITLE
C-M-g not working

### ISSUE THREAD

**Issue by feilchenfeldt** [jacktasia/dumb-jump#84]
Hello,
Thanks for developing dumb-jump.
This might rather be a issue with emac or meta-key mapping. I hope it is ok to ask this here.

I installed dumb-jump trough the package manager and everything works except for C-M-g.
(C-M-q works as expected, M-x dumb-jump-go works as expected)

When I use C-h k to check the mapping of C-M-g, then I get the mapping for C-g displayed. C-M-q however is displayed correctly.
Do you have any ideas why this could be and how to fix it? Could it have something to do with meta key mapping? I am working on a Linux cluster connected through ssh from Mac OSX using iterm. The meta-key mapping usually works for all other commands.

Many thanks,
Hannes

**Comment by jacktasia** [comment]
> Could it have something to do with meta key mapping? I am working on a Linux cluster connected through ssh from Mac OSX using iterm. The meta-key mapping usually works for all other commands.

Sounds like it. It'd be hard to help much without your emacs config, but I am guessing it has something to do with running in iTerm. I think the easiest solution would be to just map `dumb-jump-go` to something else. It's only <kbd>C-M-g</kbd> by default because that's what "jump to defintion" is in IntelliJ's Emacs mode.

`(global-set-key (kbd "C-c g") 'dumb-jump-go)`

**Comment by feilchenfeldt** [comment]
Thanks, that works!
