### ISSUE TITLE
use ack (or another search utility) instead of grep

### ISSUE THREAD

**Issue by kolewu** [jacktasia/dumb-jump#9]
There are now far better alternatives to searching with grep, that now about files to ignore like the `.git` repository and how to find the root of a project.

- [Beyond grep: ack 2.14, a source code search tool for programmers](http://beyondgrep.com/)
- [The Silver Searcher](http://geoff.greer.fm/ag/) a lot faster than ack
- [sift - a fast and powerful alternative to grep](https://sift-tool.org/)
- [the_platinum_searcher: A code search tool similar to ack and the_silver_searcher(ag)](https://github.com/monochromegane/the_platinum_searcher)  It supports multi platforms and multi encodings.

**Comment by jacktasia** [comment]
Thanks. I do plan on adding support for other search programs and I am aware of the alternatives. The reason I did not support a better searcher initially is because they are not installed on most systems by default and this is a barrier to "just working".

Right now my plan is to add support for `ag` because it seems like it's the fastest one that is in all the common package managers, but please correct if I am wrong. Then by default it would use `ag` if it was available and fallback to `grep` only if it had to. With the future goal of allowing any searcher.

That said, totally open to other opinions (and PRs) on the best way to do this. I will keep this issue open until a faster searcher is being used by default. Thanks again for opening!

**Comment by jacktasia** [comment]
Hi @kolewu 

Yesterday I added support for the silver searcher (`ag`). Dumb Jump will now default to using `ag` if it's available and then fallback to using `grep` if it must. In my tests, it's way faster, particularly when jumping through emacs .el.gz source code. If you get a chance to try it, please let me know.

**Comment by jacktasia** [comment]
Closing this for now since `ag` support is now in place. Feel free to re-open and/or comment if you have any feedback. Thanks!

**Comment by kolewu** [comment]
Thank you for this quick implementation.  Now I'm waiting for a project where I can benefit from this package ;-)
